### ISSUE TITLE
Amend breadcrumbs

### ISSUE THREAD

**Issue by apricot13** [moodleou/moodle-mod_subpage#10]
You mention in your readme that you have added the extra level to your breadcrumbs in your theme, would you be able to share any relevant code relating to that? Even if you consider it hacky it would be a great help!

**Comment by sammarshallou** [comment]
Hi, unfortunately you cannot attach files to github issues and it's too long to paste in. If you give me your email address I will email you our theme/ou/renderers/core_renderer.php. However it is very complicated and contains a bunch of stuff you're not going to need, so it'll probably be very difficult to use (and I definitely don't have time to help you with it unfortunately)...

**Comment by apricot13** [comment]
Thank you! my email is hannah at healthcare-learning.com you may have to end the files with .txt our firewall wont let php files through.

I did manage to bodge a fix, (what else is to be expected with moodle!) but I've already found some flaws in my approach!
