### ISSUE TITLE
Future of Subpage plugin

### ISSUE THREAD

**Issue by aspark21** [moodleou/moodle-mod_subpage#12]
Hi Sam,

Have you had any further thoughts about the future of the plugin?

The plugin is now 2.8 ready but the Readme is still indicating that it might be dropped for 2.8.

I know other universities and hosting providers have taken the warning as it definitely not being supported anymore.

Just thinking it might be worth updating the readme either way.

Thanks for the awesome plugin!
A big fan

**Comment by sammarshallou** [comment]
Thanks! You have a good point, I've edited the readme. We definitely do plan to stop using it at some point but we will need to continue using it for existing courses, so that will include Moodle 2.9 and probably the next several versions after that as well.
