### ISSUE TITLE
"Copy sub-page" functionality gives error

### ISSUE THREAD

**Issue by doiphode** [moodleou/moodle-mod_subpage#20]
When attempting to use the "Copy sub-page" functionality it fails after selecting the destination with the error "Exception - Class 'format_oustudyplan\features' not found"

This does not, however, seem to be an issue when using backup and restore.

**Comment by sammarshallou** [comment]
Oops - thanks for reporting this, it looks like this requirement for the format_oustudyplan plugin in that part of code was introduced accidentally. It seems to be the only one in the plugin. I've done a change (in master branch only, will be in our 3.7 stable branch in December - feel free to manually apply the change to your own code if you need it in another branch) which should fix it.
